language: php
php:
    - 7.1
cache:
    directories:
        - $HOME/.composer/cache/files
services:
    - postgresql
before_install:
    - composer self-update
before_script:
  - psql -c 'create database postgres;' -U postgres
  - composer install --no-interaction
script:
    - composer test-all
